services:
  db:
    hostname: db
    container_name: postgres-databases
    image: postgres:15
    shm_size: 128mb
    env_file:
      - .docker/.env.development
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - bank-net

  adminer:
    hostname: adminer
    container_name: adminer-bank-system
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - bank-net

  dozzle:
    hostname: dozzle
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_ADDR=:9999
      - DOZZLE_ENABLE_ACTIONS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:9999
    networks:
      - bank-net

volumes:
  pg_data:

networks:
  bank-net: